# Generated by Django 5.2.8 on 2026-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_contact", models.CharField(max_length=15)),
                ("recipient_address", models.TextField()),
                ("recipient_pincode", models.IntegerField()),
                (
                    "recipient_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("sender_pincode", models.IntegerField()),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sender_address", models.TextField(blank=True, null=True)),
                (
                    "sender_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("weight", models.FloatField()),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("volumetric_weight", models.FloatField(blank=True, null=True)),
                ("applicable_weight", models.FloatField(blank=True, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("cod", "Cash on Delivery"), ("prepaid", "Prepaid")],
                        default="prepaid",
                        max_length=10,
                    ),
                ),
                ("order_value", models.FloatField(default=0.0)),
                ("item_type", models.CharField(blank=True, max_length=100, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(default=1)),
                ("item_amount", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("booked", "Booked"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "selected_carrier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_cost", models.FloatField(blank=True, null=True)),
                ("cost_breakdown", models.JSONField(blank=True, null=True)),
                ("awb_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "zone_applied",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mode", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_number"], name="orders_order_n_1336be_idx"
                    ),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                    models.Index(
                        fields=["created_at"], name="orders_created_77e2b9_idx"
                    ),
                    models.Index(
                        fields=["selected_carrier"], name="orders_selecte_ce0cbe_idx"
                    ),
                ],
            },
        ),
    ]
