# Generated by Django 5.2.8 on 2026-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("booked", "Booked / Ready to Ship"),
                    ("manifested", "Manifested"),
                    ("picked_up", "Picked Up / In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled / Unbooked"),
                    ("pickup_exception", "Pickup Exception"),
                    ("ndr", "NDR (Non-Delivery Report)"),
                    ("rto", "RTO (Return to Origin)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FTLOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("source_city", models.CharField(max_length=100)),
                ("destination_city", models.CharField(max_length=100)),
                ("source_pincode", models.IntegerField()),
                ("destination_pincode", models.IntegerField()),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("20FT", "20FT"),
                            ("32 FT SXL 7MT", "32 FT SXL 7MT"),
                            ("32 FT SXL 9MT", "32 FT SXL 9MT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_price", models.FloatField()),
                ("escalation_amount", models.FloatField()),
                ("price_with_escalation", models.FloatField()),
                ("gst_amount", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("booked", "Booked / Ready to Ship"),
                            ("manifested", "Manifested"),
                            ("picked_up", "Picked Up / In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled / Unbooked"),
                            ("pickup_exception", "Pickup Exception"),
                            ("ndr", "NDR (Non-Delivery Report)"),
                            ("rto", "RTO (Return to Origin)"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ftl_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_number"], name="ftl_orders_order_n_a2381b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ftl_orders_status_2a0853_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ftl_orders_created_5a45a3_idx"
                    ),
                ],
            },
        ),
    ]
