# Generated by Django 5.2.8 on 2026-01-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0002_alter_order_status_ftlorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftlorder",
            name="source_address",
            field=models.TextField(default="Address not provided"),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
