# Generated by Django 5.2.8 on 2026-01-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0003_ftlorder_source_address_alter_ftlorder_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ftlorder",
            name="booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
