# Generated by Django 5.2.8 on 2026-01-03 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courier", "0004_ftlorder_booked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ftlorder",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price before escalation",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="escalation_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="15% of base price", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="18% GST on price_with_escalation",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="price_with_escalation",
            field=models.DecimalField(
                decimal_places=2, help_text="Base + escalation", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="ftlorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Final total price", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="item_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Item amount",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Order value for COD",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total shipping cost",
                max_digits=12,
                null=True,
            ),
        ),
    ]
